### ISSUE TITLE
feat(): Add version/cache-busting support for component-specific JavaScript and CSS files

### ISSUE THREAD

**Issue by anna777x** [dotnetcore/BootstrapBlazor#6834]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

After updating BootstrapBlazor to a newer version in our production Blazor application, users encountered errors due to browser cache mismatches. The error occurred because the browser cached old component-specific JavaScript files (e.g., AutoComplete.razor.js)
This created a mismatch where old JavaScript tried to invoke methods with signatures that changed in the new version.

Example error:
System.ArgumentException: The type 'AutoFill'1' does not contain a public invokable method with [InvokeableMethodAttribute('OnKeyUp')]

The issue was resolved only after users performed a hard refresh (Ctrl+F5), forcing the browser to bypass the cache and download the updated JavaScript files.

The main bundle file (bootstrap.blazor.bundle.min.js?v=2025.10.3.2) already includes version query strings (because we have access to naming of this file).
Component-specific files (like AutoComplete.razor.js, Modal.razor.js, etc.) are served without version parameters.
This causes aggressive browser caching with no automatic invalidation on library updates

Proposed Solution:
Add automatic version/cache-busting to all component-specific JavaScript and CSS files. This could be implemented through: Query string versioning: Append library version or content hash to component JS/CSS files like AutoComplete.razor.js?v=8.10.0

### Additional context

<img width="653" height="147" alt="Image" src="https://github.com/user-attachments/assets/9fa6ce96-0972-4372-9233-4f16fa58ec42" />

**Comment by ArgoZhang** [comment]
@anna777x sorry this is bug. I'll fix it right away. thank you for report this issue. could you give this project a star?

**Comment by ArgoZhang** [comment]
@anna777x I'm sorry I misunderstood you at first. Now I understand your problem. This problem is not something our component library can solve, but something that the Blazor framework needs to solve. This problem has been solved in Net9.

```
app.MapStaticAssets();
```

and

```
<ImportMap></ImportMap>
```


### Other

Or if you have any ideas, we can try to solve this problem.

**Comment by anna777x** [comment]
@ArgoZhang 
I appreciate you pointing me to the feature of .NET 9 solution. However, after implementing both MapStaticAssets() and <ImportMap /> in my .NET 9 project, I'm still experiencing the same cache issues with BootstrapBlazor component files.

After testing and research, I've discovered that **MapStaticAssets()** in .NET 9 **only fingerprints assets that are part of the application's direct build output**. Unfortunately, it does not automatically version:
 - Static assets from NuGet packages
 - Razor Class Library (RCL) assets served from _content/ paths
 - Third-party library components

This means that files like:
_content/BootstrapBlazor/Components/AutoComplete.razor.js
_content/BootstrapBlazor/Components/Modal.razor.js
...and so on are being served with the old cached version.

I'd like to respectfully suggest that the library implement versioning for component static assets (js/css).

The library could **automatically append the package version to component script** references when they're loaded. 
For example, instead of:
_content/BootstrapBlazor/Components/AutoComplete.razor.js
It would be:
_content/BootstrapBlazor/Components/AutoComplete.razor.js?v=9.0.1

**Comment by ArgoZhang** [comment]
@anna777x hi. thank you for the reply. could you show me your `App.razor` code. it' should be

```
<link rel="stylesheet" href="@Assets["_content/BootstrapBlazor.FontAwesome/css/font-awesome.min.css"]" />
<link rel="stylesheet" href="@Assets["_content/BootstrapBlazor.MaterialDesign/css/md.min.css"]" />
<link rel="stylesheet" href="@Assets["_content/BootstrapBlazor.BootstrapIcon/css/bootstrap.min.css"]" />
<link rel="stylesheet" href="@Assets["_content/BootstrapBlazor/css/bootstrap.blazor.bundle.min.css"]" />
<link rel="stylesheet" href="@Assets["_content/BootstrapBlazor/css/motronic.min.css"]" />
<link rel="stylesheet" href="@Assets["BootstrapBlazor.Server.styles.css"]" />
<link rel="stylesheet" href="@Assets["css/site.css"]" />

<ImportMap></ImportMap>
```

the point is `<ImportMap></ImportMap>`

<img width="3010" height="1654" alt="Image" src="https://github.com/user-attachments/assets/35b63343-98f5-4204-b3d3-0294fa4cd414" />

now. you can see the orgin file `AutoComplete.razor.js` instead of `AutoComplete.fdy6b1jcii.razor.js`

This function is completed by ImportMap

**Comment by ArgoZhang** [comment]
@anna777x sorry, the above reply is a bit hasty. I also found that there will be some problems when referencing third-party packages.

Is there any idea to add v=9.0.1? This is a very complicated and tedious task.

**Comment by ArgoZhang** [comment]
@anna777x could you have a try `9.11.1-beta05`. it's works on my localhost

**Comment by anna777x** [comment]
@ArgoZhang Unfortunately, it didn’t help because the library assets need their own versioning mechanism, MapStaticAssets() and  helper @ Assets don’t handle them. like I mentioned: MapStaticAssets() and the @ Assets only work for assets in your project, not for Razor Class Library (RCL) assets from NuGet packages.

**Comment by ArgoZhang** [comment]
@anna777x thank you for the feedback. please try the follow mini-repro-project. it's really works on my local host.

[BootstrapBlazorApp2.Server.zip](https://github.com/user-attachments/files/22787799/BootstrapBlazorApp2.Server.zip)

<img width="3010" height="1826" alt="Image" src="https://github.com/user-attachments/assets/e53d4d02-ad15-4375-97af-d0819ed0123a" />

**Comment by ArgoZhang** [comment]
@anna777x resolved please try `v9.11.2-beta01`

**Comment by anna777x** [comment]
@ArgoZhang I apologize, but the changes in v9.11.2-beta01 didn’t resolve the issue.

There’s an explanation from AI, maybe this approach will work better.

<img width="867" height="686" alt="Image" src="https://github.com/user-attachments/assets/fdd7c6f1-56c8-49b2-9bc1-dff58b76b890" />


And a few references to highlight these nuances of MapStaticAssets():
https://www.peug.net/en/dotnet-9-cache-busting-blazor/   - **last warning in the article**
https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-9.0#static-asset-delivery-optimization   - **about limitation of MapStaticAssets**
https://github.com/dotnet/aspnetcore/discussions/59101

**Thank you for your continued attention to this issue!**

**Comment by ArgoZhang** [comment]
@anna777x Have you tried it? I understand your point, I can tell you some of the details I updated.

This problem has been solved by net10. So I currently use net10 to package the automation script, so the current package supports adding fingerprints to the xxx.razor.js file.


### Prove

```
<StaticWebAssetEndpoint Include="_content/BootstrapBlazor/Components/Anchor/Anchor.g5z1athxxe.razor.js">
  <AssetFile>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\staticwebassets\Components\Anchor\Anchor.razor.js'))</AssetFile>
  <Selectors><![CDATA[[]]]></Selectors>
  <EndpointProperties><![CDATA[[{"Name":"fingerprint","Value":"g5z1athxxe"},{"Name":"integrity","Value":"sha256-zGkaeC1AnJPGuOwx5XUZgR3CR04m0h2YghZ8A9H5Fp0="},{"Name":"label","Value":"_content/BootstrapBlazor/Components/Anchor/Anchor.razor.js"},{"Name":"script-type","Value":"module"}]]]></EndpointProperties>
  <ResponseHeaders><![CDATA[[{"Name":"Cache-Control","Value":"max-age=31536000, immutable"},{"Name":"Content-Length","Value":"1511"},{"Name":"Content-Type","Value":"text/javascript"},{"Name":"ETag","Value":"\u0022zGkaeC1AnJPGuOwx5XUZgR3CR04m0h2YghZ8A9H5Fp0=\u0022"},{"Name":"Last-Modified","Value":"Fri, 10 Oct 2025 06:48:55 GMT"}]]]></ResponseHeaders>
</StaticWebAssetEndpoint>
<StaticWebAssetEndpoint Include="_content/BootstrapBlazor/Components/Anchor/Anchor.razor.js">
  <AssetFile>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\staticwebassets\Components\Anchor\Anchor.razor.js'))</AssetFile>
  <Selectors><![CDATA[[]]]></Selectors>
  <EndpointProperties><![CDATA[[{"Name":"integrity","Value":"sha256-zGkaeC1AnJPGuOwx5XUZgR3CR04m0h2YghZ8A9H5Fp0="},{"Name":"script-type","Value":"module"}]]]></EndpointProperties>
  <ResponseHeaders><![CDATA[[{"Name":"Cache-Control","Value":"no-cache"},{"Name":"Content-Length","Value":"1511"},{"Name":"Content-Type","Value":"text/javascript"},{"Name":"ETag","Value":"\u0022zGkaeC1AnJPGuOwx5XUZgR3CR04m0h2YghZ8A9H5Fp0=\u0022"},{"Name":"Last-Modified","Value":"Fri, 10 Oct 2025 06:48:55 GMT"}]]]></ResponseHeaders>
</StaticWebAssetEndpoint>
```

`_content/BootstrapBlazor/Components/Anchor/Anchor.g5z1athxxe.razor.js` the fingerprint link already generated in `9.11.2-beta02` nuget package


So. if you app use `NET9` all the `bootstrapblazor` asset will automatically add fingerprints.

please submit a mini-repo-project if you have any question.
